export const books = [
  {
    id: '1',
    title: 'My First Book',
    summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    genre: 'Fiction',
    lastModified: 'April 4, 2025',
    chapters: [
      { id: '1', title: 'Chapter 1', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada.' },
      { id: '2', title: 'Chapter 2', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada.' },
    ]
  },
  {
    id: '2',
    title: 'My Second Book',
    genre: 'Thriller',
    summary: 'A deep dive into the unknown.',
    lastModified: 'April 3, 2025',
    chapters: [
      { id: '1', title: 'Introduction', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla imperdiet ullamcorper nisi et mattis. Maecenas condimentum lacus magna, et dignissim ante mattis a. Morbi eget dictum dui. Nullam a ex vitae nisi convallis efficitur vel in diam. Nam nec quam ornare, placerat lacus eget, interdum enim. Aliquam porta porta purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis semper pellentesque vestibulum. Nullam pellentesque eget est non laoreet. Donec sit amet feugiat diam, sed rutrum arcu. Sed fringilla enim eu porttitor posuere. Duis luctus mauris quis varius auctor. Donec vehicula varius neque, sit amet tincidunt orci tempor id. Nam tincidunt vehicula felis, in tincidunt justo iaculis nec. Sed pharetra tristique malesuada.' },
    ]
  }
]
